### ISSUE TITLE
HomeAssistant integration

### ISSUE THREAD

**Issue by bragg2012** [prcolaco/avalon-nano-cli#1]
Hey not an issue just after some guidance on how you integrated this with HomeAssistant so the cli can be triggered there based on automations/states etc?

Many thanks

**Comment by prcolaco** [comment]
Exactly, using `trigger` and `shell_command`... you can trigger it at specific times or based on automations, like solar panels producing energy. So much fun! 🤙

**Comment by bragg2012** [comment]
Great, thanks for the quick reply I’ll check those out!
